// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function List() {
  return window['go']['main']['App']['List']();
}

export function Run(arg1, arg2) {
  return window['go']['main']['App']['Run'](arg1, arg2);
}
