// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function List() {
  return window['go']['main']['App']['List']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function OnSecondInstanceLaunch(arg1) {
  return window['go']['main']['App']['OnSecondInstanceLaunch'](arg1);
}

export function Run(arg1, arg2, arg3) {
  return window['go']['main']['App']['Run'](arg1, arg2, arg3);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}
