name: Wails build

on: [pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build:
          [
            {
              name: Browser Profile Launcher.exe,
              platform: windows/amd64,
              os: windows-latest,
            },
            {
              name: browser-profile-launcher,
              platform: darwin/universal,
              os: macos-latest,
              package: false,
            },
          ]
    runs-on: ${{ matrix.build.os }}
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - uses: dAppServer/wails-build-action@main
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          package: false
