name: Wails release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        build:
          [
            {
              name: Browser Profile Launcher.exe,
              platform: windows/amd64,
              os: windows-latest,
            },
            {
              name: Browser Profile Launcher.app,
              platform: darwin/universal,
              os: macos-latest,
              package: false,
            },
          ]
    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dAppServer/wails-build-action@v2
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          package: true
